#!/bin/bash

# Cowrie Installation Script

# Update system
echo "Updating system..."
sudo apt update && sudo apt upgrade -y

# Install dependencies
echo "Installing dependencies..."
sudo apt install -y git python3-virtualenv libssl-dev libffi-dev build-essential libpython3-dev python3-minimal authbind

# Create a dedicated user for Cowrie
sudo adduser --disabled-password --gecos "" cowrie

# Switch to the cowrie user
sudo -u cowrie -H sh -c 'cd ~ && git clone http://github.com/cowrie/cowrie'

# Create virtual environment
sudo -u cowrie -H sh -c 'cd ~/cowrie && python3 -m venv cowrie-env'

# Activate virtual environment
sudo -u cowrie -H sh -c 'source ~/cowrie/cowrie-env/bin/activate && cd ~/cowrie && pip install --upgrade pip'

# Install Cowrie
sudo -u cowrie -H sh -c 'source ~/cowrie/cowrie-env/bin/activate && cd ~/cowrie && pip install -r requirements.txt'

# Configure Cowrie
sudo -u cowrie -H sh -c 'cp ~/cowrie/cowrie.cfg.dist ~/cowrie/cowrie.cfg'

# Start Cowrie (can be done manually or via systemd)
echo "Cowrie installed successfully. You can start it manually by running: "
echo "sudo -u cowrie -H sh -c 'source ~/cowrie/cowrie-env/bin/activate && cd ~/cowrie && ./start.sh'"
