#!/bin/bash

# Cowrie Installation Script

# Update system
echo "Updating system..."
sudo apt update 
sudo apt install git
sudo apt install iptables
chmod -R 777 honeypot

# Install dependencies
echo "Installing dependencies..."
sudo apt install -y git python3-virtualenv libssl-dev libffi-dev build-essential libpython3-dev python3-minimal authbind

# Create a dedicated user for Cowrie
sudo adduser --disabled-password --gecos "" cowrie
chown -R cowrie:cowrie /home/cowrie/*

# Switch to the cowrie user
sudo su - cowrie 
sudo git clone http://github.com/cowrie/cowrie
chmod -R 777 cowrie
cd cowrie

# Create virtual environment
python -m venv cowrie-env

# Activate virtual environment
source cowrie-env/bin/activate 
python -m pip install --upgrade pip
python -m pip install --upgrade -r requirements.txt


# Configure Cowrie
sudo cp cowrie.cfg.dist cowrie.cfg

# Start Cowrie (can be done manually or via systemd)
bin/cowrie start
echo "Cowrie installed successfully. You can start it manually by running: "
