#!/bin/bash

# Cowrie Installation and Running Script

# Update system
echo "Updating system..."
sudo apt update -y
sudo apt install iptables -y

# Install dependencies
echo "Installing dependencies..."
sudo apt-get install git python3-virtualenv libssl-dev libffi-dev build-essential libpython3-dev python3-minimal authbind virtualenv

# Create a dedicated user for Cowrie
sudo adduser --disabled-password --gecos "" cowrie

# Switch to the cowrie user
sudo -u cowrie -H 'cd ~ && git clone http://github.com/cowrie/cowrie'

# Create virtual environment
sudo -u cowrie -H 'cd ~/cowrie && python -m venv cowrie-env'

# Activate virtual environment
sudo -u cowrie -H 'source ~/cowrie/cowrie-env/bin/activate && cd ~/cowrie && python -m pip install --upgrade pip'

# Install Cowrie
sudo -u cowrie -H 'source ~/cowrie/cowrie-env/bin/activate && cd ~/cowrie && python -m pip install --upgrade -r requirements.txt'

# Configure Cowrie
sudo -u cowrie -H 'source ~/cowrie/cowrie-env/bin/activate && cp ~/cowrie/etc/cowrie.cfg.dist ~/cowrie/cowrie.cfg'

# Start Cowrie
echo "Starting Cowrie with logging..."
sudo -u cowrie -H 'source ~/cowrie/cowrie-env/bin/activate && cd ~/cowrie && bin/cowrie start'

# Open log
sudo -u cowrie -H 'source ~/cowrie/cowrie-env/bin/activate && cd ~/cowrie/var/log/cowrie && tail -f cowrie.log'
