#!/bin/bash

DISPLAY_USAGE="true"

install_deps () {
	sudo apt-get update
	sudo apt-get iptables
	sudo apt install git

}

check_os () {
	# check for debian and debian version
	if [ ! -f "/etc/debian_version" ]
	then
	 	echo "No debian_version file present, is this Debian?"
		exit
	fi
}

create_user () {
	echo "Creating user account..."
	adduser cowrie --disabled-password cowrie
	sudo su - cowrie
}

set_permissions () {
	chown -R raspberry:raspberry /home/raspberry/honeypot
}
		
install_honey() {
	sudo git clone http://github.com/cowrie/cowrie
	cd cowrie
	chmod -R 777 cowrie

	cd /home/raspberry
}



usage () {
	echo "Usage:"
	echo "./honey [-i]"
	echo ""
        echo "-i        Install everything."
       
}

while [[ $# -gt 0 ]]
do
	DISPLAY_USAGE="false"
	key="$1"

	case $key in
 		-i|--install)
			echo "Install..."
			check_os
			install_deps
			create_user
			install_honey
			shift
			;;
	
	    	*)
			usage
			shift
	    		;;
	esac
done

if [ "$DISPLAY_USAGE" = true ]
then
	usage
fi

exit
