#!/bin/bash

# Cowrie Installation and Running Script

# Update system
echo "Updating system..."
sudo apt update -y
sudo apt install iptables -y

# Install dependencies
echo "Installing dependencies..."
sudo apt-get install git python3-virtualenv libssl-dev libffi-dev build-essential libpython3-dev python3-minimal authbind virtualenv

# Create a dedicated user for Cowrie
sudo adduser --disabled-password --gecos "" cowrie
sudo -u cowrie -c 'git clone https://github.com/cowrie/cowrie'
sudo -u cowrie -c 'cd /home/cowrie'
sudo -u cowrie -c 'python -m venv cowrie-env'
sudo -u cowrie -c 'source cowrie-env/bin/activate'
sudo -u cowrie -c 'python -m pip install --upgrade pip && python -m pip install --upgrade -r requirements.txt'
sudo -u cowrie -c 'cp etc/cowrie.cfg.dist etc/cowrie.cfg'
sudo -u cowrie -c 'bin/cowrie start'

