#!/bin/bash

DISPLAY_USAGE="true"

install_depend () {
	apt-get install git python3-virtualenv libssl-dev libffi-dev build-essential libpython3-dev python3-minimal authbind virtualenv
}

install_cowrie () {
	apt-get update
	apt-get install iptables
	apt-get install git
	git clone http://github.com/cowrie/cowrie
	cd cowrie
}

exist() {
	if [ -d "/home/raspberry/honeypot/" ]
	then
		echo "/home/raspberry/honeypot already exists. Remove it and rerun install"
		exit
	fi
	cd /home/raspberry/honeypot
}

setup_envi () {
	if [ -d "/home/raspberry/honeypot" ]
	then
		python -m venv cowrie-env
	  source cowrie-env/bin/activate
	  python -m pip install --upgrade pip
	  python -m pip install --upgrade -r requirements.txt
}

check_os () {
	# check for debian and debian version
	if [ ! -f "/etc/debian_version" ]
	then
	 	echo "No debian_version file present, is this Debian?"
		exit
	fi
}

start_cowrie () {
	bin/cowrie start
}


usage () {
	echo "Usage:"
	echo "./honeypot [-i]"
	echo ""
  echo "-i        Install."
}

while [[ $# -gt 0 ]]
do
	DISPLAY_USAGE="false"
	key="$1"

	case $key in
 		-i|--install)
			echo "Install..."
			check_os
			install_depend
			install_honeypot
	esac
done

if [ "$DISPLAY_USAGE" = true ]
then
	usage
fi

exit
