#!/bin/bash 

install_package () {
sudo apt update
sudo apt install git
sudo apt install iptables
sudo apt-get install git python3-virtualenv libssl-dev libffi-dev build-essential libpython3-dev python3-minimal authbind virtualenv
}

install_cowrie () {
sudo git clone http://github.com/cowrie/cowrie
cd cowrie
}

setup_environment () {
python -m venv cowrie-env
source cowrie-env/bin/activate
python -m pip install --upgrade pip
python -m pip install --upgrade -r requirements.txt
}

start_cowrie () {
bin/cowrie start
}
